config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :communities, param: :name
  patch '/community/:name/join', to: 'communities#join'
  patch '/community/:name/leave', to: 'communities#leave'
  resources :post
  devise_for :user, controllers: { registrations: 'registrations' }
  get 'user/:id', to: 'user#show'
  root 'post#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/community.rb
# frozen_string_literal: true

# Community Model
class Community < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  validates :name, uniqueness: true

  def to_param
    name
  end
end

app/models/membership.rb
# frozen_string_literal: true

class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :community
  validates :user_id, uniqueness: { scope: :community_id }
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  belongs_to :community
  validates :message, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :communities, through: :memberships
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/communities_controller.rb
# frozen_string_literal: true

# Communities Controller
class CommunitiesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  before_action :find_community, only: %i[show join leave]

  def new
    @community = Community.new
  end

  def create
    @community = Community.new(creation_params)
    @community.users << current_user
    if @community.save
      redirect_to community_path(name: @community.name), notice: 'Community created successfully.'
    else
      redirect_to new_community_path, notice: 'That community already exists.'
    end
  end

  def show; end

  def join
    if @community.users.include?(current_user)
      redirect_to community_path(name: @community.name), notice: "You are already a member of #{@community.name}."
    else
      @community.users << current_user
      @community.save
      redirect_to community_path(name: @community.name), notice: "Successfully joined #{@community.name}."
    end
  end

  def leave
    if @community.users.delete(current_user)
      redirect_to community_path(name: @community.name), notice: "Successfully left #{@community.name}."
    else
      redirect_to community_path(name: @community.name), notice: "Looks like you aren't a member of #{@community.name}."
    end
  end

  private

  def find_community
    @community = Community.find_by(name: params[:name])
  end

  def creation_params
    params.require(:community).permit(:name)
  end
end

app/controllers/post_controller.rb
# frozen_string_literal: true

# Posts Controller
class PostController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def index
    @posts = Post.all
  end

  def new
    @communities = Community.all
    if @communities.length.zero?
      redirect_to new_community_path, notice: 'No Communities exist yet. Please create a community first.'
    else
      @post = current_user.posts.build
    end
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path
    else
      redirect_to new_post_path, alert: 'Post unsuccessful. Please make sure you have selected a community.'
    end
  end

  private

  def post_params
    params.require(:post).permit(:message, :community_id)
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username)
  end
end

app/controllers/user_controller.rb
# frozen_string_literal: true

# User Controller
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/registrations_helper.rb
# frozen_string_literal: true

module RegistrationsHelper
end

app/views/communities/new.html.erb
<div class='container'>
  <h2>Create a community</h1>
  <%= form_for :community, url: communities_path do |f| %>
    <div class="mb-3">
      <%= f.label :name, class: "form-label" %>
      <%= f.text_field :name, class: "form-control", rows: "3" %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/communities/show.html.erb
<div class='community-header'>
  <div class='community-banner'></div>
  <div class='container'>
    <h1 class='community-title'><%= @community.name %></h1>
    <% if current_user.communities.include?(@community) %>
      <%= link_to 'Leave', "/community/#{@community.name}/leave", method: :patch, class: "btn btn-primary ms-2 community-join" %>
    <% else %>
      <%= link_to 'Join', "/community/#{@community.name}/join", method: :patch, class: "btn btn-primary ms-2 community-join" %>
    <% end %>
    <p class='community-header-name'>s/<%= @community.name %></h2>
  </div>
</div>
<div class='container'>
  <div class='row'>
    <div class='posts-container col'>
      <% @community.posts.reverse_each do |post| %>
        <%= render 'shared/post', post: post %>
      <% end %>
    </div>
    <div class='community-right-side container col-lg-4'>
      <div class='community-about'>
        <div class='community-about-title-container'>
          <p class='community-about-title'>About Community</p>
        </div>
        <div class='community-about-text-container'>
          <p class='community-about-text'>Here is some example text. This will eventually be something input by the user probably with a ruby tag</p>
        </div>
        <div class='community-members-container'>
          <p class='community-members'>
          <% if @community.users.count == 1 %>
            1 Member
          <% else %>
            <%= @community.users.count %> Members
          <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <%= image_tag "seddit_logo.png", id: "nav_logo" %>
      <h1 id="nav_title">Seddit</h1>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ms-auto">
        <% if user_session %>
          <%= link_to "New Post", new_post_path, class: "btn btn-outline-primary ms-2" %>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-primary ms-2" %>
        <% else %>
          <%= link_to "Log In", new_user_session_path, class: "btn btn-outline-primary ms-2" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary ms-2" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_notice_and_alerts.html.erb
<% if notice %>
  <p class="notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <title>Seddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/notice_and_alerts' %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  </body>
</html>

app/views/post/index.html.erb
<div class="container">
  <% @posts.reverse_each do |post| %>
    <%= render 'shared/post', post: post do %>
      <%= link_to "s/#{post.community.name}", community_path(post.community.name) %>
    <% end %>
  <% end %>
</div>

app/views/post/new.html.erb
<div class="container">
  <%= form_for :post, url: post_index_path do |f| %>
    <div class="mb-3">
      <% communities_array = @communities.map { |community| ["s/" + community.name, community.id] } %>
      <%= f.label :community_id, 'Community', class: "form-label" %>
      <%= f.select :community_id, communities_array, prompt: "Select a Community", class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :message, class: "form-label" %>
      <%= f.text_area :message, class: "form-control", rows: "3" %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shared/_post.html.erb
<div class='post'>
  <div class='votes-container'>
    <p class='votes'>0</p>
  </div>
  <div class='post-body'>
    <div class='community-name'>
      <%= yield %>
      <span class='post-user'> • Posted by <%= link_to "u/#{post.user.username}", "/user/#{post.user.id}", class: "post-username" %></span>
    </div>
    <p class='post-message'><%= post.message %></p>
  </div>
</div>

app/views/user/show.html.erb
<div class="container">
  <%= @user.username %>
  <% @user.communities.each do |community| %>
    <p><%= community.name %></p>
  <% end %>
</div>